### ISSUE TITLE
Registering to the webiste is painful.

### ISSUE THREAD

**Issue by Ankit404butfound** [TheShubhendra/pygita#2]
I am trying to register and every now and then it says "Oops! There's something wrong with our server. We'll be back as soon as possible." Would be great if you use other "direct API".

**Comment by TheShubhendra** [comment]
Sorry for the inconvenience, Actually there are some problems in the website,but still you can register your app.
1. Sign in or register yourself on website.
2. Go to https://bhagavadgita.io/account/manage/apps
and create your app
3. get yout client_id and client_secret

**Comment by Ankit404butfound** [comment]
Still  "Oops! There's something wrong with our server. We'll be back as soon as possible."
